accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/manage-users/', views.manage_users, name="manage_users"),
    path('accounts/search-users/', views.ajax_search_users, name='ajax_search_users'),

    path('accounts/create-user/', views.create_user, name="create_user"),
    path('accounts/edit-profile/<int:pk>/', views.edit_profile, name="edit_profile"),
    path('accounts/read-user/<int:pk>', views.read_profile, name='read_profile'),
    path('accounts/change-user-group/<int:pk>', views.change_user_group, name='change_user_group'),

    path('accounts/delete-user/<int:pk>', views.delete_user, name='delete_user'),
]

fournisseur/urls.py
from django.urls import path
from . import views

app_name = 'fournisseur'

urlpatterns = [
    path('fournisseur', views.fourniss_list, name='fourniss_list'),
    path('fournisseur/create_fournis', views.create_fournis, name='create_fournis'),
    path('fournisseur/read-fourniss/<int:pk>', views.read_fournisseur, name='read_fournis'),
    path('fournisseur/update-fourniss/<int:pk>', views.update_fourniss, name='update_fourniss'),
    path('fournisseur/delete-fourniss/<int:pk>', views.delete_fourniss, name='delete_fourniss'),

    path('fournisseur/fournisseur_detail/<int:fourniss_id>', views.fourniss_detail, name='fourniss_detail'),
]

inv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magasin.urls', namespace='magasin')),
    path('', include('fournisseur.urls', namespace='fournisseur')),
    path('', include('accounts.urls', namespace='accounts')),
]

magasin/urls.py
from django.urls import path
from . import views

app_name = 'magasin'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),                                           # dashboard

    # Magasin URLS
    path('magasin', views.article_list, name='article_list'),
    path('magasin/<slug:category_slug>/', views.article_list, name='article_list_by_category'),
    # STOCK ALARM
    path('magasin/stock_alarm/<int:stock_alarm>', views.article_list, name='stock_alarm'),
    # Article Sans Prix
    path('magasin/art_sans_prix/<int:art_sans_prix>', views.article_list, name='art_sans_prix'),
    # Total des Articles
    path('magasin/total_article', views.total_articles, name='total_articles'),

    # Article Details
    path('magasin/<int:art_id>/<slug:slug>/', views.article_detail, name='article_detail'),

    # Category urls
    path('magasin/create-category', views.create_category, name='create_category'),
    path('magasin/update-category/<int:cat_id>', views.update_category, name='update_category'),
    path('magasin/delete-category/<int:cat_id>', views.delete_category, name="delete_category"),

    # Articles urls
    path('magasin/create-article', views.create_article, name='create_article'),
    path('magasin/upload-articles', views.upload_articles_from_excel, name='upload_articles'),
    path('magasin/download_exemple_articles', views.download_exemple_articles, name='download_exemple_articles'),
    path('magasin/read-article/<int:art_id>/<slug:slug>', views.read_article, name='read_article'),

    # Edit Article
    path('magasin/update-article/<int:art_id>/<slug:slug>', views.update_article, name='update_article'),
    # Entree, Sortie Article Bs-Model
    path('magasin/entree-article/<int:art_id>', views.entree_article_ajax, name='entree_ajax'),      # new entry
    path('magasin/sortie-article/<int:art_id>', views.sortie_article_ajax, name='sortie_ajax'),      # new sortie
    # delete article
    path('magasin/delete-article/<int:art_id>', views.delete_article, name='delete_article'),
    path('magasin/missing-code-finder', views.missing_code_finder, name='missing_code_finder'),  # find missing code

    # -----------------------------------------------------------
    # History
    path('magasin/history', views.magasin_log, name='magasin_log'),                         # article history
    path('magasin/history/<int:art_id>/', views.magasin_log, name='magasin_log_article'),   # article history

    # -----------------------------------------------------------
    # Movement
    path('magasin/movement', views.movement, name='movement'),                          # All movement
    path('magasin/movement/<int:art_id>/', views.movement, name='movement_article'),    # Movement by article.
    path('magasin/movement/etats', views.etats, name='etats'),                          # etats journalier, mensuel
    path('magasin/delete-movement/<int:pk>', views.delete_movement, name='delete_movement'),  # delete movement

    # -----------------------------------------------------------
    # Commands urls
    path('magasin/commands', views.manage_command, name='manage_command'),                    # all commands
    path('magasin/commands/<int:pk>', views.activate_commande, name='activate_commande'),   # Active Command
    path('magasin/create-command/<int:art_id>', views.create_commande, name='create_commande'),   # Commande Details

    path('magasin/read-command/<int:pk>', views.read_commande, name='read_commande'),   # Commande Details
    path('magasin/update-commande/<int:pk>', views.update_commande, name='update_commande'),
    path('magasin/delete-commande/<int:pk>', views.delete_commande, name='delete_commande'),
]

magasin/views.py
import os
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, FileResponse, Http404
from django.utils.timezone import now

from django.db import transaction
from django.db.models import Q, Count, Sum, F
from django.contrib.auth.models import User
from accounts.models import Profile

from . import forms
from . import models
from . import functions
import pandas as pd
from datetime import date


@login_required
def dashboard(request):
    hijri = functions.hijri_()
    nbar = 'dashboard'

    # Articles Statistics
    total_command = models.Command.objects.count()
    total_articles = models.Article.objects.count()
    stock_alarm = models.Article.objects.filter(qte=0).count()
    total_valeur = models.Article.objects.aggregate(total_valeur=Sum('valeur'))['total_valeur']
    pending_command = models.Command.objects.filter(status=0).select_related('user_id')
    latest_movement = models.Movement.objects.order_by('-movement_date')[:5]
    # Users Statistics
    today = now().date()
    current_month = now().month

    # total users
    total_users = User.objects.count()
    users_today = User.objects.filter(date_joined__date=today).count()
    users_month = User.objects.filter(date_joined__month=current_month).count()
    active_users = User.objects.filter(is_active=True).count()
    inactive_users = User.objects.filter(is_active=False).count()
    group_counts = list(Profile.objects.values('groupe').annotate(count=Count('groupe')))
    job_title_counts = list(Profile.objects.values('poste_travaille').annotate(count=Count('poste_travaille')))

    from django.core.serializers.json import DjangoJSONEncoder
    import json

    context = {
        'nbar': nbar, 'hijri': hijri,
        'total_articles': total_articles,
        'total_valeur': total_valeur,
        'stock_alarm': stock_alarm,
        'total_command': total_command,
        'pending_command': pending_command,
        'latest_movement': latest_movement,
        # users
        'total_users': total_users,
        'users_today': users_today,
        'users_this_month': users_month,
        'active_users': active_users,
        'inactive_users': inactive_users,
    }
    context['group_counts_json'] = json.dumps(group_counts, cls=DjangoJSONEncoder)
    context['job_title_counts_json'] = json.dumps(job_title_counts, cls=DjangoJSONEncoder)

    return render(request, 'magasin/article/dashboard.html', context)


@login_required
def article_list(request, category_slug=None, stock_alarm=False, art_sans_prix=False):
    nbar = 'magasin'
    hijri = functions.hijri_()
    search_word = None
    categories = models.Category.objects.all()

    # Search for an article
    if request.method == 'POST':
        search_article_form = forms.SearchForm(request.POST)
        if search_article_form.is_valid():
            search_word = search_article_form.cleaned_data['search_word']
    else:
        search_article_form = forms.SearchForm()

    # filtering and searching for article
    articles, category, count = functions.filter_articles(
        search_word=search_word,
        category_slug=category_slug,
        stock_alarm=stock_alarm,
        art_sans_prix=art_sans_prix
    )

    # Add pagination to our site
    # instantiate the Paginator with the number of objects to display
    paginator = Paginator(articles, 30)
    page = request.GET.get('page')          # indicate the current page number.

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)

    context = {
        'nbar': nbar, 'hijri': hijri,
        'category': category,
        'categories': categories,
        'articles': articles,
        'search_article_form': search_article_form,
        'page': page,
        'stock_alarm': stock_alarm,
        'count': count,
        'search_word': search_word
    }
    return render(request, 'magasin/article/list.html', context)


# ----------------------------------------------------------------------
# ==> Articles Views
# ------------------------
#
# ==> Article Details View
@login_required
def article_detail(request, art_id, slug, history=False, movement=False):
    hijri = functions.hijri_()
    article = get_object_or_404(models.Article, art_id=art_id, slug=slug)

    # art_movement = models.Movement.objects.filter(art_id=art_id) or ''
    art_movement = models.Movement.objects.filter(art_id=art_id) or 'empty'
    art_cmd = models.Command.objects.filter(art_id=art_id) or 'empty'
    art_history = models.MagasinLog.objects.filter(art_id=art_id) or 'empty'

    if art_history != 'empty': history = True
    if art_movement: movement = True

    # Search for article with code
    if request.method == 'POST' and 'search_form' in request.POST:
        search_form = forms.SearchForm(request.POST)
        if search_form.is_valid():
            code = search_form.cleaned_data['search_word'].upper()
            try:
                art = models.Article.objects.get(code=code)
                return redirect('magasin:article_detail', art_id=art.art_id, slug=art.slug)
            except models.Article.DoesNotExist:
                messages.warning(request, f'Aucun article trouvé avec le code « {code} »')
                return redirect('magasin:article_detail', art_id=art_id, slug=slug)
    else:
        search_form = forms.SearchForm()

    # ----------------------------------------------------------------
    # Entree form
    # ----------------
    # ----------------------------------------------------------------
    # Modification form
    # ----------------
    if request.method == 'POST' and 'update_art' in request.POST:
        update_art_form = forms.ArticalForm(request.POST, instance=article)
        if update_art_form.is_valid():
            article.save()
            messages.info(request, 'Article Modifier avec Succés')
            return redirect('magasin:article_detail', art_id=article.art_id, slug=article.slug)
    else:
        update_art_form = forms.ArticalForm(instance=article)

    # ----------------------------------------------------------------
    # commande form
    # this is the place where create a new commande
    # ----------------
    if request.method == 'POST' and 'cmnd_form' in request.POST:
        command_form = forms.CreateCommandForm(request.POST)     # PdrSearchForm comme from forms.py file
        if command_form.is_valid():
            # form fields passed validation
            cd = command_form.cleaned_data
            models.Command.objects.create(
                art_id=article, user_id=request.user,
                command_date=cd['cmnd_date'], qte=cd['cmnd_qte']
            )

            messages.info(request, 'Commande Ajouter avec Succés')
            return redirect('magasin:article_detail', art_id=article.art_id, slug=article.slug)
    else:
        command_form = forms.CreateCommandForm()

    context = {
        'hijri': hijri,
        'article': article,
        'history': history,
        'movement': movement,
        'search_form': search_form,
        'article_mov': art_movement,
        'art_history': art_history,
        'art_cmd': art_cmd,             # commande
        'update_art_form': update_art_form,
        'command_form': command_form,
    }

    return render(request, 'magasin/article/detail.html', context)


# -----------------------------------------------------
# ==> Create Category View
@csrf_exempt
def create_category(request):
    if request.method == 'POST':
        form = forms.CreateCategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            return JsonResponse({'success': True, 'message': f"✅ Category {category.name} Enregistrés avec succés"})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = forms.CreateCategoryForm()

    return render(request, 'magasin/article/create_category.html', {'form': form})


# == Edit Category
def update_category(request, cat_id):
    category = get_object_or_404(models.Category, cat_id=cat_id)
    if request.method == 'POST':
        form = forms.CreateCategoryForm(request.POST, instance=category)
        if form.is_valid():
            updated_category = form.save()
            return JsonResponse(
                {
                    'success': True,
                    'message': f'✅ Catégory {updated_category.name} Modifier avec succés.'
                }
            )
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = forms.CreateCategoryForm(instance=category)

    context = {'form': form, 'category': category}
    return render(request, 'magasin/article/update_category.html', context)


# == Delete Category
def delete_category(request, cat_id):
    if request.method == 'POST':
        category = get_object_or_404(models.Category, cat_id=cat_id)
        cat_name = category.name
        category.delete()
        return JsonResponse({'success': True, 'message': f"✅ Catégorie {cat_name} supprimée avec succés."})
    else:
        return JsonResponse({'success': False, 'error': "❌ Une erreur s’est produite"})


# -----------------------------------------------------
# ==> Create Article View
@csrf_exempt
@login_required
def create_article(request):
    today = date.today()
    if request.method == 'POST':
        form = forms.ArticalForm(request.POST)

magasin/templates/magasin/base.html
{% load static %}

<!DOCTYPE html>
<html data-bs-theme="light" lang="en">
    <head>
    <title>{% block title %}{% endblock %}</title>


        <!-- Bootstrap -->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap-icons.min.css" %}">
        <link rel="stylesheet" href="{% static "css/sweetalert2.min.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">

    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg mr-auto border-bottom border-body fixed-top bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "magasin:dashboard" %}">Inventory</a><!--HOME-->
                <button class="navbar-toggler" type="button" 
                        data-bs-toggle="collapse" data-bs-target="#app-nav" 
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="app-nav">
                    <ul class="navbar-nav me-auto">
                        {% if request.user.is_authenticated %}
                        <!-- Home -->
                        <li class="nav-item ">
                            <a class="nav-link {% if nbar == "magasin" %}active{% endif %}" 
                               href="{% url "magasin:article_list" %}">
                                <i class="bi bi-house"></i> Magasin
                            </a>
                        </li>
                        <!-- Commands -->
                        <li class="nav-item ">
                            <a class="nav-link {% if nbar == "command" %}active{% endif %}" 
                               href="{% url "magasin:manage_command" %}">
                                <i class="bi bi-truck-flatbed"></i> Commands
                            </a>
                        </li>
                        <!-- Fournisseur -->
                        <li class="nav-item">
                            <a class="nav-link {% if nbar == "fournisseur" %}active{% endif %}"  
                               href="{% url "fournisseur:fourniss_list" %}">
                                <i class="bi bi-truck me-1"></i>Fournisseur
                            </a>
                        </li>
                        <!-- Movement -->
                        <li class="nav-item ">
                            <a class="nav-link {% if nbar == "movement" %}active{% endif %}" 
                               href="{% url "magasin:movement" %}">
                                <i class="bi bi-arrow-repeat"></i> Movement
                            </a>
                        </li>
                        <!-- History -->
                        <li class="nav-item ">
                            <a class="nav-link {% if nbar == "history" %}active{% endif %}" 
                               href="{% url "magasin:magasin_log" %}">
                                <i class="bi bi-clock"></i> History
                            </a>
                        </li>
                        {% comment %}
                        <!-- Actions Dropdown -->
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" href="#" id="actionDropdown" role="button" 
                               data-bs-toggle="dropdown" aria-expanded="false">
                               <i class="bi bi-database-gear"></i> &nbsp;Actions
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="actionDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url "magasin:stock_alarm" 1 %}">
                                        <i class="bi bi-alarm"></i> Stock Alarm
                                    </a>
                                </li>

                                <li>
                                    <a class="dropdown-item" href="{% url "magasin:art_sans_prix" 1 %}">
                                        <i class="bi bi-journal-minus"></i> Article Sans Prix
                                    </a>
                                </li>

                                <li><hr class="dropdown-divider"></li>
                                
                                <li>
                                    <a id="totalsModal"class="dropdown-item" href="#" 
                                       data-form-url="{% url "magasin:total_articles" %}">
                                        <i class="bi bi-currency-dollar"></i> Total Des Produits
                                    </a>
                                </li>
                            </ul>
                        </li> <!-- end of dropdown -->
                        {% endcomment %}
                        {% endif %}  <!-- end of user.is_authenticated -->
                        <div class="vr"></div>      <!-- Divider -->
                        <!-- date -->
                        <span class="navbar-text hijri_date fw-bold px-4">
                            <i class="bi bi-calendar-day"></i>
                            <span dir='ltr'>
                                {{ hijri.day_gr }}  {{ hijri.month_name_gr }}  {{ hijri.year_gr }} 
                            </span>
                            ---
                            {{ hijri.day_name }}: {{ hijri.day }} {{ hijri.month_name }} {{ hijri.year }}
                        </span>
                        <div class="vr"></div>      <!-- Divider -->
                    </ul><!-- end of navbar-nav -->

                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item dropdown ms-auto ">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                                   role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person"></i>&nbsp;{{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu navbar-right login-div" 
                                    aria-labelledby="navbarDropdown">                                    
                                    {% if request.user.profile.groupe == 'admin' %}
                                        <li>
                                            <a class="dropdown-item" 
                                               href="{% url "accounts:manage_users"%}">
                                                <i class="bi bi-person-lines-fill"></i>&nbsp; 
                                                Manage Users
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a href="#" class="dropdown-item" id="toggle-theme">
                                            <i class="bi bi-moon-stars"></i>&nbsp; Dark
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url "accounts:logout" %}">
                                            <i class="bi bi-box-arrow-in-right"></i> &nbsp;Logout
                                        </a>
                                    </li>
                                </ul>
                            </li><!-- end of nav-item -->
                        </ul><!-- end of nav-bar right item -->
                    {% else %}
                        <!-- Login  url -->
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item ms-auto">
                                <a class="nav-link" href="{% url "accounts:login" %}"><i class="bi bi-sign-in-alt"></i> Login</a>
                            </li>
                        </ul>
                    {% endif %} <!-- end of login or logged-in users -->

                </div><!-- end of collapse-nav -->
            </div><!-- end of navbar container -->
        </nav>


        <div class="container-fluid">
            <div id="successAlert" class="alert alert-info alert-dismissible d-none" role="alert">                
            </div>
                
            {% block content %}{% endblock %}

            <!-- Modal -->
            <div class="modal fade" id="mainModal" 
                 tabindex="-1" aria-labelledby="mainModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content" id="modalContent"></div>
                </div>
            </div>
        </div>

        <!-- Bootstrap popper and jQuery and the main custom scripts-->
        <script src='{% static "js/jQuery-3.7.1.js" %}'></script>
        <script src='{% static "js/bootstrap.bundle.min.js" %}'></script>
        <script src='{% static "js/sweetalert2.all.min.js" %}'></script>
        <script src='{% static "js/chart.js" %}'></script>
        <script src='{% static "js/main.js" %}'></script>
    </body>
</html>