accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/manage-users/', views.manage_users, name="manage_users"),
    path('accounts/search-users/', views.ajax_search_users, name='ajax_search_users'),

    path('accounts/create-user/', views.create_user, name="create_user"),
    path('accounts/edit-profile/<int:pk>/', views.edit_profile, name="edit_profile"),
    path('accounts/read-user/<int:pk>', views.read_profile, name='read_profile'),
    path('accounts/change-user-group/<int:pk>', views.change_user_group, name='change_user_group'),

    path('accounts/delete-user/<int:pk>', views.delete_user, name='delete_user'),
]

inv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magasin.urls', namespace='magasin')),
    path('', include('fournisseur.urls', namespace='fournisseur')),
    path('', include('accounts.urls', namespace='accounts')),
]

magasin/urls.py
from django.urls import path
from . import views

app_name = 'magasin'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),                                           # dashboard

    # Magasin URLS
    path('magasin', views.article_list, name='article_list'),
    path('magasin/<slug:category_slug>/', views.article_list, name='article_list_by_category'),
    # STOCK ALARM
    path('magasin/stock_alarm/<int:stock_alarm>', views.article_list, name='stock_alarm'),
    # Article Sans Prix
    path('magasin/art_sans_prix/<int:art_sans_prix>', views.article_list, name='art_sans_prix'),
    # Total des Articles
    path('magasin/total_article', views.total_articles, name='total_articles'),

    # Article Details
    path('magasin/<int:art_id>/<slug:slug>/', views.article_detail, name='article_detail'),

    # Category urls
    path('magasin/create-category', views.create_category, name='create_category'),
    path('magasin/update-category/<int:cat_id>', views.update_category, name='update_category'),
    path('magasin/delete-category/<int:cat_id>', views.delete_category, name="delete_category"),

    # Articles urls
    path('magasin/create-article', views.create_article, name='create_article'),
    path('magasin/upload-articles', views.upload_articles_from_excel, name='upload_articles'),
    path('magasin/download_exemple_articles', views.download_exemple_articles, name='download_exemple_articles'),
    path('magasin/read-article/<int:art_id>/<slug:slug>', views.read_article, name='read_article'),

    # Edit Article
    path('magasin/update-article/<int:art_id>/<slug:slug>', views.update_article, name='update_article'),
    # Entree, Sortie Article Bs-Model
    path('magasin/entree-article/<int:art_id>', views.entree_article_ajax, name='entree_ajax'),      # new entry
    path('magasin/sortie-article/<int:art_id>', views.sortie_article_ajax, name='sortie_ajax'),      # new sortie
    # delete article
    path('magasin/delete-article/<int:art_id>', views.delete_article, name='delete_article'),
    path('magasin/missing-code-finder', views.missing_code_finder, name='missing_code_finder'),  # find missing code

    # -----------------------------------------------------------
    # History
    path('magasin/history', views.magasin_log, name='magasin_log'),                         # article history
    path('magasin/history/<int:art_id>/', views.magasin_log, name='magasin_log_article'),   # article history

    # -----------------------------------------------------------
    # Movement
    path('magasin/movement', views.movement, name='movement'),                          # All movement
    path('magasin/movement/<int:art_id>/', views.movement, name='movement_article'),    # Movement by article.
    path('magasin/movement/etats', views.etats, name='etats'),                          # etats journalier, mensuel
    path('magasin/delete-movement/<int:pk>', views.delete_movement, name='delete_movement'),  # delete movement

    # -----------------------------------------------------------
    # Commands urls
    path('magasin/commands', views.manage_command, name='manage_command'),                    # all commands
    path('magasin/commands/<int:pk>', views.activate_commande, name='activate_commande'),   # Active Command
    path('magasin/create-command/<int:art_id>', views.create_commande, name='create_commande'),   # Commande Details

    path('magasin/read-command/<int:pk>', views.read_commande, name='read_commande'),   # Commande Details
    path('magasin/update-commande/<int:pk>', views.update_commande, name='update_commande'),
    path('magasin/delete-commande/<int:pk>', views.delete_commande, name='delete_commande'),
]

magasin/views.py
import os
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, FileResponse, Http404
from django.utils.timezone import now

from django.db import transaction
from django.db.models import Q, Count, Sum, F
from django.contrib.auth.models import User
from accounts.models import Profile

from . import forms
from . import models
from . import functions
import pandas as pd
from datetime import date


@login_required
def dashboard(request):
    hijri = functions.hijri_()
    nbar = 'dashboard'

    # Articles Statistics
    total_command = models.Command.objects.count()
    total_articles = models.Article.objects.count()
    stock_alarm = models.Article.objects.filter(qte=0).count()
    total_valeur = models.Article.objects.aggregate(total_valeur=Sum('valeur'))['total_valeur']
    pending_command = models.Command.objects.filter(status=0).select_related('user_id')
    latest_movement = models.Movement.objects.order_by('-movement_date')[:5]
    # Users Statistics
    today = now().date()
    current_month = now().month

    # total users
    total_users = User.objects.count()
    users_today = User.objects.filter(date_joined__date=today).count()
    users_month = User.objects.filter(date_joined__month=current_month).count()
    active_users = User.objects.filter(is_active=True).count()
    inactive_users = User.objects.filter(is_active=False).count()
    group_counts = list(Profile.objects.values('groupe').annotate(count=Count('groupe')))
    job_title_counts = list(Profile.objects.values('poste_travaille').annotate(count=Count('poste_travaille')))

    from django.core.serializers.json import DjangoJSONEncoder
    import json

    context = {
        'nbar': nbar, 'hijri': hijri,
        'total_articles': total_articles,
        'total_valeur': total_valeur,
        'stock_alarm': stock_alarm,
        'total_command': total_command,
        'pending_command': pending_command,
        'latest_movement': latest_movement,
        # users
        'total_users': total_users,
        'users_today': users_today,
        'users_this_month': users_month,
        'active_users': active_users,
        'inactive_users': inactive_users,
    }
    context['group_counts_json'] = json.dumps(group_counts, cls=DjangoJSONEncoder)
    context['job_title_counts_json'] = json.dumps(job_title_counts, cls=DjangoJSONEncoder)

    return render(request, 'magasin/article/dashboard.html', context)


@login_required
def article_list(request, category_slug=None, stock_alarm=False, art_sans_prix=False):
    nbar = 'magasin'
    hijri = functions.hijri_()
    search_word = None
    categories = models.Category.objects.all()

    # Search for an article
    if request.method == 'POST':
        search_article_form = forms.SearchForm(request.POST)
        if search_article_form.is_valid():
            search_word = search_article_form.cleaned_data['search_word']
    else:
        search_article_form = forms.SearchForm()

    # filtering and searching for article
    articles, category, count = functions.filter_articles(
        search_word=search_word,
        category_slug=category_slug,
        stock_alarm=stock_alarm,
        art_sans_prix=art_sans_prix
    )

    # Add pagination to our site
    # instantiate the Paginator with the number of objects to display
    paginator = Paginator(articles, 30)
    page = request.GET.get('page')          # indicate the current page number.

    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        articles = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results
        articles = paginator.page(paginator.num_pages)

    context = {
        'nbar': nbar, 'hijri': hijri,
        'category': category,
        'categories': categories,
        'articles': articles,
        'search_article_form': search_article_form,
        'page': page,
        'stock_alarm': stock_alarm,
        'count': count,
        'search_word': search_word
    }
    return render(request, 'magasin/article/list.html', context)


# ----------------------------------------------------------------------
# ==> Articles Views
# ------------------------
#
# ==> Article Details View
@login_required
def article_detail(request, art_id, slug, history=False, movement=False):
    hijri = functions.hijri_()
    article = get_object_or_404(models.Article, art_id=art_id, slug=slug)

    # art_movement = models.Movement.objects.filter(art_id=art_id) or ''
    art_movement = models.Movement.objects.filter(art_id=art_id) or 'empty'
    art_cmd = models.Command.objects.filter(art_id=art_id) or 'empty'
    art_history = models.MagasinLog.objects.filter(art_id=art_id) or 'empty'

    if art_history != 'empty': history = True
    if art_movement: movement = True

    # Search for article with code
    if request.method == 'POST' and 'search_form' in request.POST:
        search_form = forms.SearchForm(request.POST)
        if search_form.is_valid():
            code = search_form.cleaned_data['search_word'].upper()
            try:
                art = models.Article.objects.get(code=code)
                return redirect('magasin:article_detail', art_id=art.art_id, slug=art.slug)
            except models.Article.DoesNotExist:
                messages.warning(request, f'Aucun article trouvé avec le code « {code} »')
                return redirect('magasin:article_detail', art_id=art_id, slug=slug)
    else:
        search_form = forms.SearchForm()

    # ----------------------------------------------------------------
    # Entree form
    # ----------------
    # ----------------------------------------------------------------
    # Modification form
    # ----------------
    if request.method == 'POST' and 'update_art' in request.POST:
        update_art_form = forms.ArticalForm(request.POST, instance=article)
        if update_art_form.is_valid():
            article.save()
            messages.info(request, 'Article Modifier avec Succés')
            return redirect('magasin:article_detail', art_id=article.art_id, slug=article.slug)
    else:
        update_art_form = forms.ArticalForm(instance=article)

    # ----------------------------------------------------------------
    # commande form
    # this is the place where create a new commande
    # ----------------
    if request.method == 'POST' and 'cmnd_form' in request.POST:
        command_form = forms.CreateCommandForm(request.POST)     # PdrSearchForm comme from forms.py file
        if command_form.is_valid():
            # form fields passed validation
            cd = command_form.cleaned_data
            models.Command.objects.create(
                art_id=article, user_id=request.user,
                command_date=cd['cmnd_date'], qte=cd['cmnd_qte']
            )

            messages.info(request, 'Commande Ajouter avec Succés')
            return redirect('magasin:article_detail', art_id=article.art_id, slug=article.slug)
    else:
        command_form = forms.CreateCommandForm()

    context = {
        'hijri': hijri,
        'article': article,
        'history': history,
        'movement': movement,
        'search_form': search_form,
        'article_mov': art_movement,
        'art_history': art_history,
        'art_cmd': art_cmd,             # commande
        'update_art_form': update_art_form,
        'command_form': command_form,
    }

    return render(request, 'magasin/article/detail.html', context)


# -----------------------------------------------------
# ==> Create Category View
@csrf_exempt
def create_category(request):
    if request.method == 'POST':
        form = forms.CreateCategoryForm(request.POST)
        if form.is_valid():
            category = form.save()
            return JsonResponse({'success': True, 'message': f"✅ Category {category.name} Enregistrés avec succés"})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = forms.CreateCategoryForm()

    return render(request, 'magasin/article/create_category.html', {'form': form})


# == Edit Category
def update_category(request, cat_id):
    category = get_object_or_404(models.Category, cat_id=cat_id)
    if request.method == 'POST':
        form = forms.CreateCategoryForm(request.POST, instance=category)
        if form.is_valid():
            updated_category = form.save()
            return JsonResponse(
                {
                    'success': True,
                    'message': f'✅ Catégory {updated_category.name} Modifier avec succés.'
                }
            )
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = forms.CreateCategoryForm(instance=category)

    context = {'form': form, 'category': category}
    return render(request, 'magasin/article/update_category.html', context)


# == Delete Category
def delete_category(request, cat_id):
    if request.method == 'POST':
        category = get_object_or_404(models.Category, cat_id=cat_id)
        cat_name = category.name
        category.delete()
        return JsonResponse({'success': True, 'message': f"✅ Catégorie {cat_name} supprimée avec succés."})
    else:
        return JsonResponse({'success': False, 'error': "❌ Une erreur s’est produite"})


# -----------------------------------------------------
# ==> Create Article View
@csrf_exempt
@login_required
def create_article(request):
    today = date.today()
    if request.method == 'POST':
        form = forms.ArticalForm(request.POST)

magasin/templates/magasin/article/create_category.html
{% load widget_tweaks %}

<form id="categoryForm" action="" method="POST" data-form-url='{% url "magasin:create_category" %}'>
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">Create Category</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">        
        <div class="form-group row mb-3">
            <label class="col-sm-3 col-form-label">Category</label>
            <div class="col-sm-9">
                {% render_field form.name class="form-control" placeholder="Category Name" %}
            </div>
        </div>
        <!-- Errors -->
        <div class="form-group row mb-2">
            <div class="col-sm-3"></div>
            <div id="formErrors" class="col-sm-9 text-danger mt-2" style="display: none;"></div>
        </div>
    </div><!--End body modal-->

    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="submit-btn btn btn-info">Create</button>
    </div><!--End of footer card-->
</form>

magasin/templates/magasin/article/create_commande.html
{% load widget_tweaks %}

<form id="createCommandeForm" action="" method="POST" 
      data-form-url='{% url "magasin:create_commande" article.art_id %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title">Nouvel Commande</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">        
        {% for field in form %}
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label fst-italic text-secondary" 
                       for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                <div class="col-sm-9">
                    {% render_field field %}
                </div>
            </div>
        {% endfor %}
        <!-- Errors -->
        <div class="form-group row mb-2">
            <div class="col-sm-3"></div>
            <div id="formErrors" class="col-sm-9 text-danger mt-2" style="display: none;"></div>
        </div>
    </div><!--End body modal-->

    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-1"></i>Close
        </button>
        <button type="submit" class="btn btn-info">Create</button>
    </div><!--End of footer card-->
</form>

magasin/templates/magasin/article/dashboard.html
{% extends "magasin/base.html" %}
{% load widget_tweaks %}
{% load humanize %}
{% load custom_filters %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container">
    <div class="home-stats text-center">
      <h2 class="text-center mb-5 mt-3 fst-italic underline">Dashboard</h2>

      <div class="row">
        <div class="col-md-3">
            <a href="{% url "magasin:manage_command" %}">
            <div class="stat total-commandes">
              <i class="bi bi-cart2"></i>
              <div class="info">
                  <div>
                      <h6>Total Commands</h6>
                      <span>{{ total_command }}</span>
                  </div>
              </div>
            </div><!-- end of stat div -->
          </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
          <a href="{% url "magasin:article_list" %}">
            <div class="stat total_arts">
              <i class="bi bi-tag"></i>
              <div class="info">
                  <div><h6>Total Articles</h6><span>{{ total_articles }}</span></div>
              </div>
            </div><!-- end of stat div -->
          </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
          <a href="#" class="bs-modal" data-form-url="{% url "magasin:total_articles"%}">
            <div class="stat total_prix">
              <div class="info">
                  <div>
                      <h6>Total Prix</h6>
                      <span class="total_valeur">{{ total_valeur|floatformat:"3"|intcomma }} DA</span>
                  </div>
              </div>
            </div><!-- end of total_arts div -->
          </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
          <a href="{% url "magasin:stock_alarm" 1 %}">
            <div class="stat stock_alarm">
              <i class="bi bi-exclamation-triangle"></i>
              <div class="info">
                  <div><h6>Stock Alarm</h6><span>{{ stock_alarm }}</span></div>
              </div>
            </div><!-- end of stat div -->
          </a>
        </div><!-- end of col-md-3 -->
      </div><!-- end of row -->
    </div><!-- end of stat container -->

<div class="container info_container my-4">
    <div class="row">
        <div class="col-sm-6">
            <div class="card shadow mb-5 bg-body rounded">
                <div class="card-header">
                    <i class="bi bi-truck"></i> Commande Non Vue
                    <span class="float-end toggle-info">
                        <i class="bi bi-caret-down"></i>
                    </span>
                </div><!-- end of card-header -->

                <div class="card-body">
                    <ul class="list-group list-group-flush p-3">
                        {% for cmd in pending_command %}
                            <figure class="border-bottom">
                                <blockquote class="blockquote">
                                    <a href="{{ cmd.art_id.get_absolute_url }}" class="text-decoration-none">
                                        {{ cmd.art_id.code }}
                                    </a>
                                </blockquote>

                                <figcaption class="blockquote-footer clear-fix">
                                    {% comment %}Someone famous in <cite title="Source Title">Source Title</cite>{% endcomment %}
                                    <b>{{ cmd.qte }} {{ cmd.art_id.umesure|lower }}</b> commandé par 
                                    <b>{{ cmd.user_id.username }} {{ cmd.user_id. }}</b>
                                    <br>
                                    Date: {{ cmd.command_date|date:"d M Y" }}
                                    {% if cmd.status == 0 %}
                                        <span class="badge bg-danger">Non Vue</span>
                                        <a href="#" 
                                           class="activateCommandeBtn btn btn-primary btn-sm float-end"
                                           data-form-url="{% url "magasin:activate_commande" cmd.command_id %}">
                                            <i class="bi bi-check2-all"></i> Activé
                                        </a>
                                    {% else %}
                                        <span class="badge bg-success">Vue</span>
                                    {% endif %}
                                </figcaption>
                            </figure>
                        {% endfor %}
                    </ul>
                </div><!-- end of card-body -->
            </div><!-- end of card-->
        </div><!-- end of col-sm-6 -->

    
        <div class="col-sm-6">
            <div class="card shadow mb-5 bg-body rounded">
                <div class="card-header">
                    <i class="bi bi-arrow-left-right"></i> Dernier Movement
                    <span class="float-end toggle-info">
                        <i class="bi bi-caret-down"></i>
                    </span>
                </div><!-- end of card-header -->

                <div class="card-body p-2">
                    <table class="table table-bordered table-hover text-center">
                        <thead class="table-secondary">
                            <tr>
                                <th scope="col">Date</th>
                                <th scope="col">User</th>
                                <th scope="col">Opération</th>
                                <th scope="col">Code</th>
                                <th scope="col">Qte</th>
                                <th scope="col">Prix-U</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for latest_mov in latest_movement %}
                            <tr>
                                <td>{{ latest_mov.movement_date|date:"d M Y" }}</td>
                                <td>{{ latest_mov.user_id.username }}</td>

                                {% if latest_mov.movement == 'Sortie' %}
                                    <td class="text-danger">{{ latest_mov.movement }}</td>
                                {% else %}
                                    <td class="text-primary">{{ latest_mov.movement }}</td>
                                {% endif %}
                                <td>
                                    <a href="{% url "magasin:movement_article" latest_mov.art_id.art_id %}">{{ latest_mov.art_id.code }}</a>
                                </td>
                                <td>{{ latest_mov.qte }}</td>
                                <td>{{ latest_mov.prix }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div><!-- end of card-body -->
            </div><!-- end of card-->
        </div><!-- end of col-sm-6 -->
    </div><!-- end of row -->

    <div class="row my-4">
        <div class="col-md-3" style="">
            <a class="card text-decoration-none py-1 px-3 border-0 shadow" style="border: 1px solid #e3ebf6 !important;"
               href="{% url "accounts:manage_users" %}">
                <div class="p-2">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-body-secondary">Total Users</span><br>
                            <span class="fw-bold fs-3 px-4">{{ total_users }}</span>
                        </div>
                        <i class="bi bi-person-lines-fill fs-2 text-info"></i>
                    </div>
                </div>
            </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
            <a class="card text-decoration-none py-1 px-3 border-0 shadow" style="border: 1px solid #e3ebf6 !important;"
                href="{% url "accounts:manage_users" %}">
                <div class="p-2">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-body-secondary">Active Users</span><br>
                            <span class="fw-bold fs-3 px-4">{{ active_users }}</span>
                        </div>
                        <i class="bi bi-person-check-fill fs-2 text-primary"></i>
                    </div>
                </div>
            </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
            <a class="card text-decoration-none py-1 px-3 border-0 shadow" style="border: 1px solid #e3ebf6 !important;"
                href="{% url "accounts:manage_users" %}">
                <div class="p-2">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-body-secondary">Inactive Users</span><br>
                            <span class="fw-bold fs-3 px-4">{{ inactive_users }}</span>
                        </div>
                        <i class="bi bi-person-slash fs-2 text-danger"></i>
                    </div>
                </div>
            </a>
        </div><!-- end of col-md-3 -->

        <div class="col-md-3">
            <a class="card text-decoration-none py-1 px-3 border-0 shadow" style="border: 1px solid #e3ebf6 !important;"
                href="{% url "accounts:manage_users" %}">
                <div class="p-2">
                    <div class="card-body d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-body-secondary">Registration</span><br>
                            <span class="text-body-secondary">Month</span>
                            <span class="fw-bold fs-3 me-4">{{ users_this_month }}</span>
                            <span class="text-body-secondary">Day</span>
                            <span class="fw-bold fs-3 ">{{ users_today }}</span>
                        </div>
                        <i class="bi bi-person-plus fs-2 text-success"></i>
                    </div>
                </div>
            </a>
        </div><!-- end of col-md-3 -->
    </div><!-- end of row -->

    <script id="group-data" type="application/json">{{ group_counts_json|safe }}</script>
    <script id="job-title-data" type="application/json">{{ job_title_counts_json|safe }}</script>

    <div class="d-flex justify-content-between">
        <div class="card">
            <div class="card-body">
                <canvas id="groupChart" width="400" height="200"></canvas>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <canvas id="jobTitleChart" width="400" height="200"></canvas>
            </div>
        </div>
    </div>
</div><!-- end of latest container -->
</div>
{% endblock %}

magasin/templates/magasin/article/entree.html
{% load widget_tweaks %}

<form id="entreeArticleForm" action="" method="POST" data-form-url='{% url "magasin:entree_ajax" article.art_id %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title text-primary"><i class="bi bi-box-arrow-in-left me-3"></i>Nouvelle Entrée</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger" style="display: none;"></div>

        <div class="form-group row mb-2" style="">
            <label class="fst-italic text-secondary col-sm-3 col-form-label" for="{{ form.slug.id_for_label }}">Code</label>
            <div class="col-sm-9">
                <input class="form-control-plaintext text-uppercase fw-bold" name="slug" value="{{ article.slug }}" readonly>
            </div>
        </div>

        <div class="form-group row mb-2">
            <label class="fst-italic text-secondary col-sm-3 col-form-label" for="{{ form.entree_date.id_for_label }}">
                Date
            </label>
            <div class="col-sm-9">
                {% render_field form.entree_date %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <label class="text-secondary fst-italic col-sm-3 col-form-label" for="{{ form.qte.id_for_label }}">Qte</label>
            <div class="col-sm-9">
                {% render_field form.qte class="form-control" value=1 %}
            </div>
        </div>

        <div class="form-group row mb-2">
            <label class="text-secondary fst-italic col-sm-3 col-form-label" for="{{ form.prix.id_for_label }}">Prix</label>
            <div class="col-sm-9">
                {% render_field form.prix class="form-control" value=article.prix %}
            </div>
        </div>
    </div><!--End body modal-->

    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-2"></i>Close
        </button>
        <button type="submit" class="btn btn-primary"><i class="bi bi-floppy"></i> Enregistré</button>
    </div><!--End of footer card-->
</form>