accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/manage-users/', views.manage_users, name="manage_users"),
    path('accounts/search-users/', views.ajax_search_users, name='ajax_search_users'),

    path('accounts/create-user/', views.create_user, name="create_user"),
    path('accounts/edit-profile/<int:pk>/', views.edit_profile, name="edit_profile"),
    path('accounts/read-user/<int:pk>', views.read_profile, name='read_profile'),
    path('accounts/change-user-group/<int:pk>', views.change_user_group, name='change_user_group'),

    path('accounts/delete-user/<int:pk>', views.delete_user, name='delete_user'),
]

inv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magasin.urls', namespace='magasin')),
    path('', include('fournisseur.urls', namespace='fournisseur')),
    path('', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    poste_travaille = models.CharField(max_length=100)
    groupe_choice = (('admin', 'Admin'), ('other', 'Other'),)
    groupe = models.CharField(max_length=10, choices=groupe_choice)

    def __str__(self):
        return 'Profile user: {}, poste_travaille: {}'.format(self.user.username, self.poste_travaille)

accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


# ------------------------------------------------
# ==| Add User
# -----------------
class UserAddForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    field_order = ['username', 'password', 'password2', 'first_name', 'last_name', 'email']

    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class ProfileAddForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['poste_travaille', 'groupe']
        widgets = {'groupe': forms.Select(attrs={'class': 'form-select'})}


# ------------------------------------------------
# ==| Edit User
# -----------------
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('poste_travaille', 'groupe')
        widgets = {'groupe': forms.Select(attrs={'class': 'form-select'})}

accounts/views.py
from django.shortcuts import render, get_object_or_404   # , redirect
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.http import JsonResponse
from django.contrib.auth import authenticate, login
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from .models import Profile
from .forms import LoginForm, UserEditForm, ProfileEditForm, UserAddForm, ProfileAddForm
from magasin import functions
# from magasin.forms import SearchForm


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        login_form = LoginForm()

    context = {'login_form': login_form}
    return render(request, 'accounts/login.html', context)


# ------------------------------------------------
# ==| Manage users
# -----------------
@login_required
def manage_users(request):
    hijri = functions.hijri_()
    users = User.objects.all().order_by('-date_joined')
    context = {'hijri': hijri, 'users': users}
    return render(request, 'accounts/manage_users.html', context)


@login_required
def ajax_search_users(request):
    """
    Search Users on keyup with AJAX
    """
    if request.method == 'GET' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        search_word = request.GET.get('search_word', '')
        users = User.objects.filter(
            Q(username__icontains=search_word) |
            Q(email__icontains=search_word) |
            Q(first_name__icontains=search_word) |
            Q(last_name__icontains=search_word) |
            Q(profile__poste_travaille__icontains=search_word)
        ).select_related('profile').order_by('-date_joined')

        html = render_to_string('accounts/users_table_rows.html', {'users': users, 'request': request})
        return JsonResponse({'success': True, 'html': html})
    return JsonResponse({'success': False, 'message': 'Requête invalide.'})


# ------------------------------------------------
# ==| Create User
@login_required
def create_user(request):
    if request.method == 'POST':
        user_form = UserAddForm(data=request.POST)
        profile_form = ProfileAddForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])   # Set the chosen password
            new_user.save()                                             # Save the User object
            cd_profile = profile_form.cleaned_data
            Profile.objects.create(
                user=new_user,
                poste_travaille=cd_profile['poste_travaille'],
                groupe=cd_profile['groupe']
            )
            return JsonResponse({'success': True, 'message': '✅ Utilisateur ajouté avec succès.'})
        else:
            errors = {
                'user_form': user_form.errors.get_json_data(),
                'profile_form': profile_form.errors.get_json_data()
            }
            return JsonResponse({'success': False, 'errors': errors})
    else:
        user_form = UserAddForm()
        profile_form = ProfileAddForm()

    return render(request, 'accounts/create_user.html', {'user_form': user_form, 'profile_form': profile_form})


# ----------------------------------------------------------------------
# ==> Read User Profile
# ---------------------
def read_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'accounts/read_profile.html', {'user': user})


# ------------------------------------------------
# ==| Edit Profile
@login_required
def edit_profile(request, pk):
    user = get_object_or_404(User, pk=pk)
    profile = get_object_or_404(Profile, user_id=pk)

    if request.method == 'POST':
        user_form = UserEditForm(instance=user, data=request.POST)
        profile_form = ProfileEditForm(instance=profile, data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return JsonResponse({'success': True, 'message': '✅ Utilisateur Modifier avec succès.'})
        else:
            errors = {
                'user_form': user_form.errors.get_json_data(),
                'profile_form': profile_form.errors.get_json_data()
            }
            return JsonResponse({'success': False, 'errors': errors})
    else:
        user_form = UserEditForm(instance=user)
        profile_form = ProfileAddForm(instance=profile)

    context = {'user': user, 'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'accounts/edit_profile.html', context)


@login_required
@require_POST
def change_user_group(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user:
        groupe = user.profile.groupe
        user.profile.groupe = 'other' if groupe == 'admin' else 'admin'
        user.profile.save()
        return JsonResponse(
            {
                'success': True,
                'message': f'✅ Utilisateur {user.username} modifie avec succés {user.profile.groupe}.'
            }
        )
    else:
        return JsonResponse({'success': False, 'error': 'User Not Found'})


# ----------------------------------------------------------------------
# ==> Delete User View (bootstrap-modal-form)
# -----------------------------------------------------
@login_required
@require_POST
def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    return JsonResponse({'success': True, 'message': f'✅ Utilisateur {user.username} supprimé avec succés.'})

accounts/templates/accounts/add_user.html
{% load widget_tweaks %}

<form id="addUserForm" action="" method="POST" data-form-url='{% url "accounts:add_user" %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title"><i class="bi bi-person-plus me-3"></i>Nouvel Utilisateur</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger mt-2" style="display: none;"></div>
        {% for field in user_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col">
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" placeholder=field.label %}
                        <div class="invalid-feedback">
                            {% for error in field.errors %}<span>{{ error }}</p>{% endfor %}
                        </div>
                    {% else %}
                        {% render_field field class="form-control" placeholder=field.label %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <hr>
        {% for field in profile_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">
                    {{ field.label }}</label>
                <div class="col">
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" placeholder=field.label%}
                        <div class="invalid-feedback">
                            {% for error in field.errors %}<span>{{ error }}</span>{% endfor %}
                        </div>
                    {% else %}
                        {% render_field field class+="form-control" placeholder=field.label %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-2"></i>Close
        </button>
        <button type="submit" class="btn btn-info"><i class="bi bi-person-plus"></i> Enregistrer</button>
    </div>
</form>

accounts/templates/accounts/create_user.html
{% load widget_tweaks %}

<form id="addUserForm" action="" method="POST" data-form-url='{% url "accounts:create_user" %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title"><i class="bi bi-person-plus me-3"></i>Nouvel Utilisateur</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger mt-2" style="display: none;"></div>
        {% for field in user_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col">
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" placeholder=field.label %}
                        <div class="invalid-feedback">
                            {% for error in field.errors %}<span>{{ error }}</p>{% endfor %}
                        </div>
                    {% else %}
                        {% render_field field class="form-control" placeholder=field.label %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <hr>
        {% for field in profile_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">
                    {{ field.label }}</label>
                <div class="col">
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" placeholder=field.label%}
                        <div class="invalid-feedback">
                            {% for error in field.errors %}<span>{{ error }}</span>{% endfor %}
                        </div>
                    {% else %}
                        {% render_field field class+="form-control" placeholder=field.label %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-2"></i>Close
        </button>
        <button type="submit" class="btn btn-info"><i class="bi bi-person-plus"></i> Enregistrer</button>
    </div>
</form>

accounts/templates/accounts/edit_profile.html
{% load widget_tweaks %}

<form id="userEditForm" action="" method="POST"
      data-form-url='{% url "accounts:edit_profile" user.id %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title"><i class="bi bi-pencil-square me-3"></i> Modifier le Profil</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger mt-2" style="display: none;"></div>
        {% for field in user_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col">
                    {% render_field field class="form-control" %}
                </div>
            </div>
        {% endfor %}
        {% for field in profile_form %}
            <div class="form-group row mb-2">
                <label class="col-sm-4 col-form-label text-secondary fst-italic" 
                       for="{{ field.id_for_label }}">{{ field.label }}</label>
                <div class="col">
                    {% render_field field class+="form-control" %}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-2"></i>Close
        </button>
        <button type="submit" class="btn btn-info"><i class="bi bi-floppy"></i> Enregistrer</button>
    </div><!--End of footer card-->
</form>

accounts/templates/accounts/login.html
{% extends "magasin/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
    <div class="col col-md-5">

        <div class="card mb-5">
            <h4 class="card-header bg-secondary text-center text-white">Login</h4>

            <div class="card-body art_details">
                <!-- Article Informations -->
                <!-- Entree Form -->
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="{{ login_form.username.id_for_label }}">Username</label>
                        <div class="col-sm-9">
                            {% if login_form.username.errors %}
                                {% render_field login_form.username class="form-control border border-danger" %}
                                {% for error in login_form.username.errors %}
                                    <p class="alert alert-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {% render_field login_form.username class="form-control" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="{{ login_form.password.id_for_label }}">Password</label>
                        <div class="col-sm-9">
                            {% if login_form.password.errors %}
                                {% render_field login_form.password class="form-control border border-danger" %}
                                {% for error in login_form.password.errors %}
                                    <p class="alert alert-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {% render_field login_form.password class="form-control" %}
                            {% endif %}
                        </div>
                    </div>
                    {% comment %}
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label" for="{{ login_form.group.id_for_label }}">Group</label>
                        <div class="col-sm-9">
                            {% if login_form.group.errors %}
                                {% render_field login_form.group class="form-control border border-danger" %}
                                {% for error in login_form.group.errors %}
                                    <p class="alert alert-danger mt-1">{{ error }}</p>
                                {% endfor %}
                            {% else %}
                                {% render_field login_form.group class="form-control" %}
                            {% endif %}
                        </div>
                    </div>
                    {% endcomment %}

                    <input type="submit" class="btn btn-info float-right" value="Login">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/manage_users.html
{% extends "magasin/base.html" %}
{% load widget_tweaks %}

{% block title %}Manage Users{% endblock %}

{% block content %}

{% for msg in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<div class="container">

    <!-- Title -->
    <h2 class="display-6 my-5 py-2 fst-italic border-bottom border-2">
        <i class="bi bi-person-lines-fill"></i>
        Gérer les utilisateurs
    </h2>
    
    <!-- ALERT DIV and Main Buttons -->   
    <div id="usersAlert" class="alert alert-info alert-dismissible d-none" role="alert"></div>

    <!-- Add user button -->
    <div class="d-flex justify-content-between my-3">
        <!-- Search form -->
        <form id="user-search-form" class="mb-3">
            <div class="input-group">
                <div class="input-group-text"><i class="bi bi-search"></i></div>
                <input type="text" name="search_word" id="searchUsersWord" size=35 
                       placeholder="Recherche utilisateur" class="form-control">
            </div>            
        </form>
        <a id="createUserBtn" class="btn btn-success float-end mb-2 mt-2" href="#" 
           data-form-url="{% url 'accounts:create_user' %}" >
            <i class="bi bi-person-plus-fill"></i> Nouvel Utilisateur
        </a>
    </div>


<table class="table table-bordered table-hover main_table">
    <!-- Main Table -->
    <thead class="table-success">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Job</th>
            <th scope="col">Groupe</th>
            <th scope="col">Last Login</th>
            <th scope="col">Operations</th>
        </tr>
    </thead>
    <tbody id="userTableBody">
        {% include 'accounts/users_table_rows.html' %}
    </tbody>
</table>
</div>
{% endblock %}

accounts/templates/accounts/read_profile.html
{% load humanize %}
<div class="modal-header text-center">
    <h3 class="modal-title"><i class="bi bi-person-lines-fill me-3"></i>Détails de l'utilisateur</h3>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body">
    <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">Username</span>
            <span class="text-capitalize">{{ user.username }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">First Name</span>
            <span class="text-capitalize">{{ user.first_name }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">Last Name</span>
            <span class="text-capitalize">{{ user.last_name }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">Email</span>
            <span>{{ user.email }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">Poste Travaille</span>
            <span>{{ user.profile.poste_travaille }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">Groupe</span>
            <span>{{ user.profile.groupe }}</span>
        </li>
    </ul>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
        <i class="bi bi-x-lg me-1"></i>Close
    </button>
</div>

accounts/templates/accounts/users_table_rows.html
{% for user in users %}
    <tr id="user-row-{{ user.id }}" class="">
        <th scope="row">{{ user.date_joined|date:"d-m-Y" }}</th>
        <td>{{ user.username }}</td>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.profile.poste_travaille }}</td>
        <td class="{% if user.profile.groupe == 'admin' %}text-info{% endif %}">
            {{ user.profile.groupe }}
        </td>
        <td >{{ user.last_login|date:"d/m/Y" }}</td>

        <td class="text-center">
            <!-- Operations buttons-->
            <!-- Read User -->
            <button class="readUserBtn btn btn-sm btn-outline-primary" 
                    data-form-url="{% url "accounts:read_profile" user.id %}"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Détail">
                <i class="bi bi-person-lines-fill"></i>
            </button>
            <!-- SuperUser -->
            {% if request.user.profile.groupe == 'admin' %}
            <!-- Update User -->
            <a class="editUserBtn btn btn-sm btn-outline-info" 
                data-form-url="{% url "accounts:edit_profile" user.id %}"
                data-bs-toggle="tooltip" data-bs-placement="bottom" title="Modifier">
                <i class="bi bi-pencil-square"></i>
            </a>
            <!-- Change User Group -->
            <button class="changeUserGroupBtn btn btn-sm btn-outline-warning" 
                    data-form-url="{% url "accounts:change_user_group" user.id %}"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" 
                    title="Changér le groupe 
                    {% if user.profile.groupe == 'admin' %}Other{% else %}Admin{% endif %}">
                <i class="bi bi-star"></i>
            </button>
                    
            <!-- Delete User -->
            <button class="deleteUserBtn btn btn-sm btn-outline-danger" data-item-id="{{ user.id }}"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Supprimé">
                <i class="bi bi-person-dash-fill"></i>
            </button>
            {% endif %} <!-- endif for checking user group -->
        </td><!-- end of operation td -->
    </tr><!-- end of table row-->
{% endfor %}