fournisseur/urls.py
from django.urls import path
from . import views

app_name = 'fournisseur'

urlpatterns = [
    path('fournisseur', views.fourniss_list, name='fourniss_list'),
    path('fournisseur/create_fournis', views.create_fournis, name='create_fournis'),
    path('fournisseur/read-fourniss/<int:pk>', views.read_fournisseur, name='read_fournis'),
    path('fournisseur/update-fourniss/<int:pk>', views.update_fourniss, name='update_fourniss'),
    path('fournisseur/delete-fourniss/<int:pk>', views.delete_fourniss, name='delete_fourniss'),

    path('fournisseur/fournisseur_detail/<int:fourniss_id>', views.fourniss_detail, name='fourniss_detail'),
]

inv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('magasin.urls', namespace='magasin')),
    path('', include('fournisseur.urls', namespace='fournisseur')),
    path('', include('accounts.urls', namespace='accounts')),
]

fournisseur/models.py
from django.db import models
from django.core.validators import EmailValidator, RegexValidator


# Create your models here.
class Fournisseur(models.Model):
    fourrnis_id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=200, unique=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    fourniture = models.CharField(max_length=255, blank=True)

    code_postal = models.IntegerField(null=True, blank=True)
    pays = models.CharField(max_length=255, blank=True)

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message='Enter a valid phone number')
    telephone = models.CharField(max_length=20, validators=[phone_regex], blank=True)

    fax = models.CharField(max_length=100, null=True)
    email = models.EmailField(unique=True, blank=True, validators=[EmailValidator])
    note = models.CharField(max_length=255, blank=True)

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created', 'nom')

    def __str__(self):
        return '{}: {}'.format(self.nom, self.address)

    def save(self, *args, **kwargs):
        self.nom = self.nom.lower()
        self.address = self.address.lower()
        # self.slug = slugify(self.code.lower())
        super(Fournisseur, self).save(*args, **kwargs)

fournisseur/forms.py
from django import forms
from .models import Fournisseur


class FournisseurForm(forms.ModelForm):
    class Meta:
        model = Fournisseur
        exclude = ['frns_id']
        widgets = {'note': forms.Textarea(attrs={'cols': 100, 'rows': 5})}
        # labels = {'': ''}
        help_texts = {
            'nom': 'Nom du Domain',
            'address': 'Addresse',
            'fourniture': 'Produit Du Fournisseur',
            'code_postal': 'Code Postal',
            'pays': 'Pays',
            'telephone': 'Telephone',
            'fax': 'Fax',
            'email': 'Email',
            'note': 'Ajouter une note',
        }
        # error_messages = {'Nom': {'max_length': 'Name can only be 20 characters in length'}}

    def clean(self):
        super(FournisseurForm, self).clean()
        nom = self.cleaned_data.get('nom').lower()
        telephone = self.cleaned_data.get('telephone').lower()
        email = self.cleaned_data.get('email').lower()

        instance = self.instance
        if Fournisseur.objects.exclude(pk=instance.pk).filter(nom=nom).exists():
            self._errors['nom'] = self.error_class(['Ce nom existe déjà pour un autre fournisseur.'])

        if Fournisseur.objects.exclude(pk=instance.pk).filter(telephone=telephone).exists():
            self._errors['telephone'] = self.error_class(['Ce téléphone existe déjà pour un autre fournisseur.'])

        if Fournisseur.objects.exclude(pk=instance.pk).filter(email=email).exists():
            self._errors['email'] = self.error_class(['Ce email existe déjà pour un autre fournisseur.'])

        return self.cleaned_data


class SearchForm(forms.Form):
    search_word = forms.CharField(max_length=50, label=False)
    search_word.widget.attrs.update({'class': 'form-control col-sm-12', 'size': '30'})

fournisseur/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

from django.db.models import Q
from django.db import transaction
from . import models
from . import forms
from magasin import functions


@login_required
def fourniss_list(request):
    hijri = functions.hijri_()
    fourniss_list = models.Fournisseur.objects.all()
    search_form = forms.SearchForm(request.POST or None)

    if request.method == 'POST' and search_form.is_valid():
        query = search_form.cleaned_data['search_word']
        fourniss_list = models.Fournisseur.objects.filter(
            Q(email__icontains=query) |
            Q(nom__icontains=query) |
            Q(telephone__icontains=query) |
            Q(address__icontains=query) |
            Q(fourniture__icontains=query)
        )

    context = {
        'hijri': hijri,
        'fourniss_list': fourniss_list,
        'search_form': search_form,
    }
    return render(request, 'fournisseur/fourniss/fourniss_list.html', context)


# ----------------------------------------------------------------------
# ==> Read Article View (django-bootstrap-modal-form)
# -----------------------------------------------------
def read_fournisseur(request, pk):
    fournis = get_object_or_404(models.Fournisseur, fourrnis_id=pk)
    return render(request, 'fournisseur/fourniss/read_fourniss.html', {'fournis': fournis})


# ----------------------------------------------------------------------
# ==> Create Fournisseur View (django-bootstrap-modal-form)
# -----------------------------------------------------
@login_required
def create_fournis(request):
    if request.method == 'POST':
        form = forms.FournisseurForm(request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    fournis = form.save()
                return JsonResponse({'success': True, 'message': f'✅ Fournisseur {fournis.nom} Enregistrés avec succés'})
            except Exception as e:
                return JsonResponse({'success': False, 'error': f'Erreur lors de l\'ajout du fournisseur: {str(e)}'})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})

    else:
        form = forms.FournisseurForm()

    context = {'form': form}
    return render(request, 'fournisseur/fourniss/create_fourniss.html', context)


def update_fourniss(request, pk):
    fourniss = get_object_or_404(models.Fournisseur, fourrnis_id=pk)
    if request.method == 'POST':
        form = forms.FournisseurForm(request.POST, instance=fourniss)
        if form.is_valid():
            updated_fourniss = form.save()
            return JsonResponse(
                {
                    'success': True,
                    'message': f'✅ Fournisseur {updated_fourniss.nom} Modifier avec succés.'
                }
            )
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = forms.FournisseurForm(instance=fourniss)

    context = {'form': form, 'fourniss': fourniss}
    return render(request, 'fournisseur/fourniss/update_fourniss.html', context)


# ==> Delete Article View (bootstrap-modal-form)
def delete_fourniss(request, pk):
    if request.method == 'POST':
        fourniss = get_object_or_404(models.Fournisseur, fourrnis_id=pk)
        fourniss.delete()
        return JsonResponse({'success': True, 'message': f'✅ Fournisseur {fourniss.nom} supprimé avec succés.'})
    return JsonResponse({'success': False, 'error': 'Invalid request'})


@login_required
def fourniss_detail(request, fourniss_id):
    hijri = functions.hijri_()
    fourniss_detail = get_object_or_404(models.Fournisseur, fourrnis_id=fourniss_id)

    context = {'hijri': hijri, 'fourniss_detail': fourniss_detail}
    return render(request, 'fournisseur/fourniss/fourniss_detail.html', context)

fournisseur/templates/fournisseur/fourniss/create_fourniss.html
{% load widget_tweaks %}

<form id="createFournissForm" action="" method="POST" 
      data-form-url='{% url "fournisseur:create_fournis" %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h5 class="modal-title">Nouveau Fournisseur</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger" style="display: none;"></div>
        
        {% for field in form %}
            <div class="form-group row mb-2">
                <label class="col-sm-3 col-form-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                <div class="col-sm-9">
                    {% render_field field class="form-control" placeholder=field.label %}
                </div>
            </div>
        {% endfor %}
    </div><!--End body modal-->

     <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-1"></i>Close
        </button>
        <button type="submit" class="btn btn-info">Create</button>
    </div><!--End of footer card-->
</form>

fournisseur/templates/fournisseur/fourniss/fourniss_list.html
{% extends "magasin/base.html" %}
{% load widget_tweaks %}

{% block title %}Fournisseur List {% endblock %}

{% block content %}
<div class="container">

<!-- Main display -->
<h2 class="display-6 my-5 py-2 fst-italic border-bottom border-2">
    <i class="bi bi-truck"></i>
    Gérer les fournisseurs
</h2>
<div id="fournisAlert" class="alert alert-info alert-dismissible d-none" role="alert"></div>
<!-- Display Messages -->
{% for msg in messages %}
    <div id="fournisAlert" class="alert alert-info alert-dismissible fade show" role="alert">
        {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        </button>
    </div>
{% endfor %}

<div class="row mb-3">
    <!-- Search form-->
    <div class="col-md-9">
        <form class="row row-cols-lg-auto align-items-center" action="" method="post">
            {% csrf_token %}
            <div class="col-12">
                <div class="input-group">
                    <div class="input-group-text"><i class="bi bi-search"></i></div>
                    {% render_field search_form.search_word placeholder="Recherche..." %}
                </div>
            </div>

            <div class="col-12">
                <button type="submit" class="btn btn-outline-primary"><i class="bi bi-search"></i></button>
            </div>
        </form>
    </div>

    <div class="col-md-3 my-2">
        {% if request.user.profile.groupe == 'admin' %}
            <button type="button" id="createFournissBtn" 
                    class="btn btn-success float-end" 
                    data-form-url="{% url "fournisseur:create_fournis" %}">
                <i class="bi bi-person-plus me-1"></i> Ajoutér 
            </button>
        {% endif %}
    </div>
</div><!-- end of search row -->

<!-- Table -->
<div class="main-table" id="article_table">
    <table class="table table-bordered table-hover main_table">
        <thead class="table-dark">
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Addresse</th>
                <th scope="col">Fourniture</th>
                <th scope="col">C-Post</th>
                <th scope="col">Pays</th>
                <th scope="col">Tel</th>
                <th scope="col">Fax</th>
                <th scope="col">Email</th>
                <th scope="col">Note</th>
                <th scope="col">Opération</th>
            </tr>
        </thead>
        <tbody>
            {% for fourniss in fourniss_list %}
                <tr id="fourniss-row-{{ fourniss.fourrnis_id }}">
                    <th scope="row">
                        <a class="text-decoration-none" href="{% url "fournisseur:fourniss_detail" fourniss.fourrnis_id %}">
                            {{ fourniss.nom|upper }}
                        </a>
                    </th>
                    <td>{{ fourniss.address|truncatechars:20 }}</td>
                    <td>{{ fourniss.fourniture|truncatechars:20 }}</td>
                    <td>{{ fourniss.code_postal }}</td>
                    <td>{{ fourniss.pays }}</td>
                    <td>{{ fourniss.telephone }}</td>
                    <td>{{ fourniss.fax }}</td>
                    <td>{{ fourniss.email|truncatechars:15 }}</td>
                    <td>{{ fourniss.note }}</td>
                    <td>
                        <div class="btn-group">
                            <!-- Read Fournisseur -->
                            <button type="button" id="read-article" 
                                    class="readFournisBtn btn btn-sm btn-outline-primary" 
                                    data-form-url="{% url "fournisseur:read_fournis" fourniss.fourrnis_id %}">
                                <i class="bi bi-eye"></i>
                            </button>
                            
                            {% if request.user.profile.groupe == 'admin' %}
                            <!-- Update Fourniss -->
                            <button class="editFournissBtn btn btn-sm btn-outline-info" 
                                    data-form-url="{% url "fournisseur:update_fourniss" fourniss.fourrnis_id %}">
                                    <i class="bi bi-pencil-square"></i>
                            </button>
                            
                            <!-- Delete Article -->
                            <button type="button" class="deleteFournissBtn btn btn-sm btn-outline-danger" 
                                    data-item-id="{{ fourniss.fourrnis_id }}">
                                <i class="bi bi-trash"></i>
                            </button>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div><!--End of main table div-->

</div><!-- end of container>
{% endblock %}

fournisseur/templates/fournisseur/fourniss/read_fourniss.html
{% load humanize %}
<div class="modal-header text-center">
    <h4 class="modal-title">
        <i class="bi bi-person me-3"></i>Detail du Fournisseur
    </h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>

<div class="modal-body">
    <ul class="list-group list-group-flush">

        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Nom
            </span>
            <span class="text-capitalize">{{ fournis.nom }}</span>
        </li>        
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Address
            </span>
            <span class="text-capitalize">{{ fournis.address }}</span>
        </li>        
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Fourniture
            </span>
            <span class="text-capitalize">{{ fournis.fourniture }}</span>
        </li>        
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Code Postale
            </span>
            <span class="text-capitalize">{{ fournis.code_postal }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Payé
            </span>
            <span class="text-capitalize">{{ fournis.pays }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Téléphone
            </span>
            <span class="text-capitalize">{{ fournis.telephone }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Fax
            </span>
            <span class="text-capitalize">{{ fournis.fax }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Email
            </span>
            <span class="text-capitalize">{{ fournis.email }}</span>
        </li>
        <li class="list-group-item d-flex align-items-center">
            <span class="text-secondary fst-italic" style="font-size: 1rem; width: 30%">
                Note
            </span>
            <span class="text-capitalize">
                {% if fournis.note %}{{ fournis.note }}{% else %}Ras{% endif %}</span>
        </li>
    </ul>        
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default border me-2" data-bs-dismiss="modal">
        <i class="bi bi-x-lg me-2"></i>Close
    </button>
</div>

fournisseur/templates/fournisseur/fourniss/update_fourniss.html
{% load widget_tweaks %}

<form id="fournissEditForm" action="" method="POST" 
      data-form-url='{% url "fournisseur:update_fourniss" fourniss.fourrnis_id %}'>
    {% csrf_token %}

    <div class="modal-header">
        <h4 class="modal-title">
            <i class="bi bi-pencil-square me-3"></i>Modification Fournisseur
        </h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div><!--End of header card-->

    <div class="modal-body">
        <div id="formErrors" class="alert alert-danger mt-2" style="display: none;"></div>

        {% for field in form %}
            <div class="form-group row mb-2">
                <label class="text-secondary fst-italic col-sm-3 col-form-label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                <div class="col-sm-9">
                    {% render_field field class="form-control" %}
                </div>
            </div>
        {% endfor %}
    </div><!--End body modal-->

    <div class="modal-footer">
        <button type="button" class="btn btn-default border" data-bs-dismiss="modal">
            <i class="bi bi-x-lg me-2"></i>Close
        </button>
        <button type="submit" class="btn btn-info"><i class="bi bi-floppy me-2"></i>Enregistré</button>
    </div><!--End of footer card-->
</form>